config/routes.rb
Rails.application.routes.draw do


  root to: 'users#new'


  get '/profil', to: 'users#edit', as: :profil
  patch '/profil', to: 'users#update'


  # Sessions

  get '/login', to: 'sessions#new', as: :new_session

  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy', as: :destroy_session



  #Route for the emails

  #resources :sessions, only: [:new, :create]
  
  resources :passwords, only: [:new, :create, :edit, :update]

  resources :users, only: [:new, :create, :edit] do

    member do

      get 'confirm'

    end

  end 
    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord


    attr_accessor :avatar_file

    has_secure_password
    has_secure_token :confirmation_token
    has_secure_token :recover_password

    after_save :avatar_after_upload
    before_save :avatar_before_upload
    after_destroy_commit :avatar_destroy

    #Validation du nom d'utilisateur et de l'email

    validates :username, 
    format:{with: /\A[a-zA-Z0-9_]{2,20}\z/, message: 'should have alphanumerical characters or dashes _'}, 
    uniqueness: {case_sensitive: false}

    validates :email, 
    format:{with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i}, 
    uniqueness: {case_sensitive: false}

    #/\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i}

    validates :avatar_file, file: {ext: [:jpg, :png]}


    def to_session

        {id: id}

    end


    def avatar_path

        File.join(
           Rails.public_path, 
           self.class.name.downcase.pluralize, 
           id.to_s, 
           'avatar.png')
   end


   def avatar_url

       '/' + [self.class.name.downcase.pluralize, 
           id.to_s, 
           'avatar.png'
       ].join('/')

   end

   private
   
    def avatar_before_upload

        if avatar_file.respond_to? :path
            self.avatar = true
        end
    end


    def avatar_after_upload

        path = avatar_path

            if avatar_file.respond_to? :path
                dir = File.dirname(path)
                FileUtils.mkdir_p(dir) unless Dir.exist?(dir)
                image = MiniMagick::Image.new(avatar_file.path) do |b|
                    b.resize '150x150^'
                    b.gravity 'Center'
                    b.crop '150x150+0+0'
                end
            image.format 'png'
            image.write path
        end
    end



    def avatar_destroy

        File.dirname(avatar_path)
        FileUtils.rm_r(dir) if Dir.exist?(dir)
    end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


    protect_from_forgery with: :exception

    before_action :only_signed_in

    add_flash_types :success, :danger

    helper_method :current_user, :user_signed_in?

    private

    def only_signed_in

        if !user_signed_in?
        #if !current_user
        #if !session[:auth] || !session[:auth]['id']
            redirect_to new_user_path, danger: 'You cannot access to this page'
        end
    end


    def user_signed_in?

        # Si c'est different de nil l'utilisateur est connecte sinon, l'utilisateur n'est pas connecte
        !current_user.nil?
    end

    def only_signed_out

        redirect_to profil_path if user_signed_in?
    end



    # Retourne l'utilisateur actuellement connecte

    def current_user

        return nil if !session[:auth] || !session[:auth]['id']
        # Si j'ai deja une variable d'instance qui s'appelle user, tu dois le retourner
        return @_user if @_user
        # @user = User.find(session[:auth]['id'])
        # Je veux trouver un enregistrement par rapport a un champ
        @_user = User.find_by_id(session[:auth]['id'])
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController

    skip_before_action :only_signed_in
    before_action :only_signed_out

    def new

    end

    def create
        user_params = params.require(:user)
        params.require(:user)
        @user = User.find_by_email(user_params[:email])

        if @user
            @user.regenerate_recover_password
            UserMailer.password(@user).deliver_now
            redirect_to new_session_path, success: 'Un email vous a été envoyé'
        else
            redirect_to new_password_path, danger: 'Aucun utilisateur ne correspond à cet email'
        end
    end

    def edit
        @user = User.find(params[:id])
        if @user.recover_password != params[:token]
            redirect_to new_password_path, danger: 'Token invalide'
        end
    end

    def update
        user_params = params.require(:user).permit(:password, :password_confirmation, :recover_password)
        @user = User.find(params[:id])
        if @user.recover_password === user_params[:recover_password]
            @user.assign_attributes(user_params)

            if @user.valid?
                @user.recover_password = nil
                @user.save
                session[:auth] = @user.to_session
                redirect_to profil_path, success: 'Votre mot de passe a bien été modifié'
            else
                render :edit
            end
        else
            redirect_to new_password_path, danger: 'Token invalide'
        end
    end

    def user_params
        
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_action :only_signed_in, only: [:new, :create]

  before_action :only_signed_out, only: [:new, :create]


  def new
  end  

  def create
    # Tout d'abord, on va creer une variable 'user_params' pour recuperer les parametres de l'utilisateur
    user_params = params.require(:user)
    # Je veux l'utilisateur qui correspond a ce qui est taper
    @user = User.where(username: user_params[:username]).or(User.where(email: user_params[:username])).first
    if @user and @user.authenticate(user_params[:password])
    session[:auth] = @user.to_session
    redirect_to profil_path, success: 'The Connection is successful'
    else
      redirect_to new_session_path, danger: 'Incorrect Identifiers'
    end
  
  end 


  def destroy
    session.destroy
    redirect_to new_session_path, success: 'You are now deconnected'
  end

  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    #Je vais creer un utilisateur qui sera un nouvelle utilisateur et je cree la vue qui correspond a cette action
    

    skip_before_action :only_signed_in, only: [:new, :create, :confirm]

    before_action :only_signed_out, only: [:new, :create, :confirm]



    def new
        @user = User.new
    end


    def create
        user_params = params.require(:user).permit(:username, :email, :password, :password_confirmation)
        @user = User.new(user_params)
        @user.recover_password = nil
        
        if @user.valid?
            @user.save
            UserMailer.confirm(@user).deliver_now
            redirect_to new_user_path, success: 'your account has been created, you have received a confirmation email to confirm your account'

            #render 'new'
        else
            render 'new'
        end
    end


    def confirm
        # Tout d'abord, on recupere l'utilisateur
        @user = User.find(params[:id])
        # On verifie le 'confirm_token' qui est passe en parametre correspond au confirm_token qui est stocke dans la base de donnee
        if @user.confirmation_token == params[:token]
            @user.update_attributes(confirmed: true, confirmation_token: nil)
            @user.save(validate: false)
            # Mon utilisateur a un compte valide; je peux le connecter et pour gerer la connection j'utilise la session
            # je cree une clef appeler 'auth' et je mets 'id: @user.id' de l'utilisateur
            # Creons une methode permettant de convertir l'utilisateur en session
            # session[:auth] = [id: @user.id]
            session[:auth] = @user.to_session
            redirect_to profil_path, success: 'Your account has been confirmed'

        else
            redirect_to new_user_path, danger: 'This token seems invalid'
        end
    end



    def edit

        #@user = User.find(session[:auth]['id'])
        @user = current_user
    end


    def update

        @user = current_user
        user_params = params.require(:user).permit(:username, :firstname, :lastname, :avatar_file, :email)
        #puts user_params[:avatar].inspect
        if @user.update(user_params)
            redirect_to profil_path, success: 'Your account has been updated'
            
        else

            render :edit
    end

end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Petsy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>
  
    <div class="navbar navbar-inverse">
      <div class="container">
       <div class="navbar-header">
        <a href="<%= root_path %>" class="navbar-brand">Petsy</a>
       </div>
       

       <ul class="nav navbar-nav navbar-right">
         <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
              <%= current_user.username %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to 'My profil', profil_path %></li>
              <li><%= link_to 'Disconnect', destroy_session_path, data: {method: :delete} %></li>
            </ul>
         </li>
        <% else %>
          <li><a href="<%= new_user_path %>">S'inscrire</a></li>
          <li><a href="<%= new_session_path %>">Se Connecter</a></li>
        <% end %>
      </ul>
  </div>
</div>


  <div class="container">
    <% if flash[:success] %>
      <div class="alert alert-success">
      <%= flash[:success] %>
      </div>
      <% end %>

      <% if flash[:danger] %>
      <div class="alert alert-danger">
      <%= flash[:danger] %>
      </div>
      <% end %>

    <%= yield %>

      <%= debug session[:auth] %>

  </div>  

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>

app/views/users/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">S'inscrire</div>
    <div class="panel-body">
      <%= form_for @user, url: profil_path, html: {class: 'form-horizontal'} do |f| %>

        <% if @user.avatar %>
        <%= image_tag @user.avatar_url %>
        <% end %>


          <div class="form-group">
                <%= f.label :avatar_file, "Avatar", class: 'col-md-4 control-label' %>
                <div class="col-md-6">
                   <%= f.file_field :avatar_file, class: 'form-control' %>
                </div>
          </div>
      

          <div class="form-group">
            <%= f.label :username, "Username", class: 'col-md-4 control-label' %>
            <div class="col-md-6">
            <%= f.text_field :username, class: 'form-control' %>
            </div>
          </div>
     
          <div class="form-group">
            <%= f.label :email, "Email", class: 'col-md-4 control-label' %>
            <div class="col-md-6">
            <%= f.email_field :email, class: 'form-control' %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label :firstname, "Firstname", class: 'col-md-4 control-label'%>
          <div class="col-md-6">
            <%= f.text_field :firstname, class: 'form-control' %>
          </div>
          </div>

          <div class="form-group">
            <%= f.label :lastname, "Lastname", class: 'col-md-4 control-label'%>
            <div class="col-md-6">
            <%= f.text_field :lastname, class: 'form-control' %>
          </div>
          </div>

          <div class="form-group">
            <div class="col-md-6 col-md-offset-4 ">
          <button type="submit" class="btn btn-primary">S'inscrire</button>
            </div>
          </div>
        <% end %>

  </div>
</div>

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<div class="panel panel-default">
  <div class="panel-heading">S'inscrire</div>
    <div class="panel-body">
      <%= form_for @user, html: {class: 'form-horizontal'} do |f| %>

        <div class="form-group">
          <%= f.label :username, "Username", class: 'col-md-4 control-label'%>
          <div class="col-md-6">
            <%= f.text_field :username, class: 'form-control' %>
          </div>
        </div>
     
        <div class="form-group">
          <%= f.label :email, "Email", class: 'col-md-4 control-label' %>
          <div class="col-md-6">
           <%= f.email_field :email, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :password, "Password", class: 'col-md-4 control-label' %>
          <div class="col-md-6">
            <%= f.password_field :password, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :password_confirmation, "Password Confirmation", class: 'col-md-4 control-label' %>
          <div class="col-md-6">
           <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group">
         <div class="col-md-6 col-md-offset-4 ">
          <button type="submit" class="btn btn-primary">S'inscrire</button>
         </div>
        </div>

    
    <% end %>
    </div>
</div>